from setuptools import setup, find_packages

setup(name="fcstmetrics",
      version="0.1.0",
      author="Robin Lee",
      python_requires=">=3.9",
      packages=find_packages(exclude=["notebooks", "notebooks.*", "tests", "tests.*"]),
      install_requires=["numpy>=1.20.0", 
                        "pandas==2.2.3", 
                        "scipy>=1.7.0", 
                        "scikit-learn>=1.0.0", 
                        "statsmodels>=0.13.0", 
                        "matplotlib>=3.4.0"],
      extras_require={"sktime": ["sktime==0.30.0"], 
                      "viz": ["seaborn>=0.11.0"], 
                      "dev": ["pytest>=7.0.0",
                              "pytest-cov>=3.0.0",
                              "black>=22.0.0",
                              "flake8>=4.0.0"]},
      entry_points={"console_scripts": ["fcstmetrics=fcstmetrics.cli:main"]})
